Repository HYU-IL/HYUIL, pull requests merged in 2024-10, with the labels that each got.

#9 Init: github actions을 이용한 자동 라벨링
  .github/labeler.yml
  .github/workflows/label.yml
Labels: :tada: INIT, :sauropod: 채영

#5 Feat : 담당 버튼 및 리스트 아이템 컴포넌트 생성
  package-lock.json
  package.json
  public/tempImage.png
  src/app/layout.tsx
  src/components/buttons/MidiumButton.tsx
  src/components/buttons/MorePopularButton.tsx
  src/components/buttons/ShowAllButton.tsx
  src/components/sliders/LargeInnerTitleItem.tsx
  src/components/sliders/SmallInnerTitleItem.tsx
  tailwind.config.ts
Labels: :sparkles: FEAT, :ghost: 채영

#17 feat: test
  .github/labeler.yml
Labels: :sparkles: FEAT, :sauropod: 채영

#7 Feat: 담당 버튼 및 리스트 아이템 컴포넌트 생성
  public/tmp.jpg
  src/app/page.tsx
  src/components/buttons/InfoButton.tsx
  src/components/buttons/MapChip.tsx
  src/components/buttons/TravelButton.tsx
  src/components/sliders/LargeListItem.tsx
  src/components/sliders/MediumInnerTitleItem.tsx
Labels: :sparkles: FEAT, :sauropod: 채영

#18 Init: github actions로 CI/CD 구축
  .github/workflows/build.yml
Labels: :tada: INIT

#6 Feat : 담당 버튼 및 리스트 아이템 컴포넌트 생성
  package-lock.json
  src/components/buttons/ChangeLocButton.tsx
  src/components/buttons/LikeorTypeButton.tsx
  src/components/buttons/WalkorCarButton.tsx
  src/components/buttons/gps.svg
  src/components/sliders/MediumListItem.tsx
  src/components/sliders/SmallListItem.tsx
  src/components/sliders/hotel.png
  tailwind.config.ts
Labels: :sparkles: FEAT, :thought_balloon: 서영

#19 Init: CI/CD 관련 shell script 생성
  build.sh
Labels: :tada: INIT

#26 Feat: 공통 color 및 typo 생성
  src/app/globals.css
  src/app/page.tsx
  src/components/buttons/MapChip.tsx
  src/components/common/CategoryTitle.tsx
  src/components/common/SubInfoTypo.tsx
  src/components/sliders/MediumInnerTitleItem.tsx
  src/styles/typo.ts
  tailwind.config.js
  tailwind.config.ts
Labels: :sparkles: FEAT, :sauropod: 채영

#27 Feat: 가로 스크롤 구현을 위한 플러그인 추가
  package-lock.json
  package.json
  src/components/sliders/LargeListItem.tsx
  src/components/sliders/MediumInnerTitleItem.tsx
  tailwind.config.js
Labels: :sparkles: FEAT, :ghost: 채영
