Repository HYU-IL/HYUIL, pull requests merged in 2024-11, with the labels that each got.

#34 feat: 고정 카드 컴포넌트 생성
  src/components/common/MediumCardItem.tsx
Labels: :sparkles: FEAT, :sauropod: 채영

#33 Feat: 메인페이지 생성
  public/assets/icons/Bell.svg
  public/assets/icons/CampingIcon.svg
  public/assets/icons/CityView.svg
  public/assets/icons/FestivalIcon.svg
  public/assets/icons/HotPlace.svg
  public/assets/icons/LeisureIcon.svg
  public/assets/icons/MainLogo.svg
  public/assets/icons/MapIcon.svg
  public/assets/icons/RecreationIcon.svg
  public/assets/icons/User.svg
  public/assets/icons/WorkationIcon.svg
  public/assets/images/BannerImage1.svg
  public/assets/images/BannerImage2.svg
  src/app/main/page.tsx
  src/components/sliders/Banner.tsx
  src/components/sliders/Carousel.tsx
  src/components/sliders/MediumListItem.tsx
  src/components/sliders/SmallListItem.tsx
  tailwind.config.js
Labels: :sparkles: FEAT

#38 Feat: 마이페이지 구현
  public/assets/icons/PinkHeart.svg
  public/assets/icons/TreeIcon.svg
  public/assets/icons/bell.svg
  public/assets/icons/clock.svg
  public/assets/icons/heart.svg
  public/assets/images/balloon.svg
  public/assets/images/tree.svg
  src/app/mypage/alert/page.tsx
  src/app/mypage/like/page.tsx
  src/app/mypage/notice/page.tsx
  src/app/mypage/page.tsx
Labels: :sparkles: FEAT

#40 Feat: 캠핑, 축제, 휴양 페이지 구현
  public/assets/icons/left.svg
  public/assets/images/Mountain.svg
  public/assets/images/Private.svg
  src/app/camping/page.tsx
  src/app/festival/page.tsx
  src/app/resort/page.tsx
  src/components/common/CategoryTitle.tsx
  src/components/common/SubInfoTypo.tsx
  src/components/sliders/MediumInnerTitleItem.tsx
  src/components/sliders/SmallListItem.tsx
  tailwind.config.js
Labels: :sparkles: FEAT, :sauropod: 채영

#42 Feat: 스플래시 및 회원가입 화면 구현
  public/assets/icons/addicon.svg
  public/assets/icons/downicon.svg
  public/assets/icons/paperplaneicon.svg
  public/assets/icons/selectedicon.svg
  public/assets/icons/upicon.svg
  public/assets/images/bg_camping.png
  public/assets/images/bg_festival.png
  public/assets/images/bg_leisure.png
  public/assets/images/bg_mountain.png
  public/assets/images/bg_ocean.png
  public/assets/images/bg_resort.png
  public/assets/images/kakaobutton.svg
  public/assets/images/logo.svg
  public/assets/images/logo_korean.svg
  public/assets/images/step_1or2_off.svg
  public/assets/images/step_1or2_on.svg
  public/assets/images/step_3or4_off.svg
  public/assets/images/step_3or4_on.svg
  public/assets/images/step_camping.svg
  public/assets/images/step_car.svg
  public/assets/images/step_car_off.svg
  public/assets/images/step_festival.svg
  public/assets/images/step_leisure.svg
  public/assets/images/step_morethan5_off.svg
  public/assets/images/step_morethan5_on.svg
  public/assets/images/step_resort.svg
  public/assets/images/step_road.svg
  public/assets/images/step_road_off.svg
  src/app/signup/_component/Splash.tsx
  src/app/signup/_component/StepCard.tsx
  src/app/signup/page.tsx
  src/styles/typo.ts
  tailwind.config.js
  tsconfig.json
Labels: :sparkles: FEAT, :sauropod: 채영

#46 Fix: img 태그에서 발생하는 빌드 에러 해결
  public/assets/icons/alert.svg
  public/assets/icons/bell.svg
  src/app/mypage/page.tsx
  src/components/sliders/Banner.tsx
  src/components/sliders/Carousel.tsx
  src/components/sliders/MediumListItem.tsx
  src/components/sliders/SmallListItem.tsx
  src/components/sliders/carousel.css
Labels: :lady_beetle: BUG

#48 Feat: 거점 컴포넌트 일부 구현
  package-lock.json
  package.json
  public/assets/icons/Close.svg
  public/assets/icons/HandleBar.svg
  src/app/foothold/page.tsx
  src/app/layout.tsx
  src/components/BottomSheet.tsx
  src/components/KakoMap.tsx
  src/components/buttons/ChangeLocButton.tsx
  src/components/buttons/WalkorCarButton.tsx
  src/components/sliders/SmallBottomSheetItem.tsx
  tailwind.config.js
  tsconfig.json
Labels: :sparkles: FEAT

#51 fix: 폰트 적용 문제 해결
  src/app/layout.tsx
  src/fonts/PretendardVariable.woff2
Labels: :lady_beetle: BUG

#56 Feat: 지도 선택 페이지 구현
  public/assets/icons/map/SelectMap_CampingChip.svg
  public/assets/icons/map/SelectMap_CampingChip_Selected.svg
  public/assets/icons/map/SelectMap_FestivalChip.svg
  public/assets/icons/map/SelectMap_FestivalChip_Selected.svg
  public/assets/icons/map/SelectMap_LeisureChip.svg
  public/assets/icons/map/SelectMap_LeisureChip_Selected.svg
  public/assets/icons/map/SelectMap_LikeChip.svg
  public/assets/icons/map/SelectMap_LikeChip_Selected.svg
  public/assets/icons/map/SelectMap_ResortChip.svg
  public/assets/icons/map/SelectMap_ResortChip_Selected.svg
  public/assets/icons/map/SelectMap_WorkationChip.svg
  public/assets/icons/map/SelectMap_WorkationChip_Selected.svg
  public/assets/images/map/Cheorwon.svg
  public/assets/images/map/Chuncheon.svg
  public/assets/images/map/Donghae.svg
  public/assets/images/map/Gangneung.svg
  public/assets/images/map/Goseong.svg
  public/assets/images/map/Hoengseong.svg
  public/assets/images/map/Hongcheon.svg
  public/assets/images/map/Hwacheon.svg
  public/assets/images/map/Inje.svg
  public/assets/images/map/Jeongseon.svg
  public/assets/images/map/Pyeongchang.svg
  public/assets/images/map/Samcheok.svg
  public/assets/images/map/Sokcho.svg
  public/assets/images/map/Taebaek.svg
  public/assets/images/map/Wonju.svg
  public/assets/images/map/Yanggu.svg
  public/assets/images/map/Yangyang.svg
  public/assets/images/map/Yeongwol.svg
  src/app/mypage/alert/page.tsx
  src/app/mypage/like/page.tsx
  src/app/mypage/notice/page.tsx
  src/app/select-map/page.tsx
  src/components/Map.tsx
  src/components/SelectMapBottomSheet.tsx
  src/components/sliders/MapSmallInnerTitleSlider.tsx
Labels: :sparkles: FEAT

#55 Feat: 더보기 페이지 구현
  public/assets/icons/Mountain.svg
  public/assets/icons/Ocean.svg
  public/assets/icons/Popular.svg
  public/assets/icons/Private.svg
  src/app/camping/more/page.tsx
  src/app/festival/more/page.tsx
  src/app/leisure/more/page.tsx
  src/app/resort/more-beach/page.tsx
  src/app/resort/more-temple/page.tsx
  src/app/resort/more/page.tsx
  src/app/workation/more/page.tsx
  src/components/common/ViewMoreBeachItem.tsx
  src/components/common/ViewMoreCampingItem.tsx
  src/components/common/ViewMoreFestivalItem.tsx
  src/components/common/ViewMoreLeisureItem.tsx
  src/components/common/ViewMoreOfficeItem.tsx
  src/components/common/ViewMoreResidenceItem.tsx
  src/components/common/ViewMoreTempleItem.tsx
Labels: :sparkles: FEAT
